---
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-",
  fig.retina = 3
)
```

# Stronger Together? Linked Fate and Voter Preferences in the 2020 Election

### A. Jordan Nafa, Meredith Walsh Niezgoda, P. DeAnne Roark, and Valerie Martinez-Ebers

### Abstract

> How do intersecting identities influence candidate preference among members of pan-ethnic racial groups? In this paper we examine how racial, gender, and intersectional dimensions of linked fate shaped candidate preferences among Asian and Latino Americans in the 2020 presidential election. Drawing on a post-election survey with a large over-sample of non-white respondents, we employ Bayesian multilevel regression with post-stratification (MrP) to examine variation in the role of linked fate within pan-ethnic identity groups. Our results suggest intersectional linked fate is a strong negative predictor of support for Trump among both Asian and Latino respondents. We also find heterogeneity in this relationship across pan-ethnic subgroups, particularly among those who express lower levels of linked fate.


## Licenses

**Text and figures:** All prose and images are licensed under Creative Commons ([CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)).

**Code:** All code is licensed under the [BSD 3-Clause License](LICENSE.md).
